version: "3.0"
services:
  php:
    image: eventsauce-messagestorage-gcp-php
    build: docker/php
    container_name: eventsauce-messagestorage-gcp-php
    working_dir: /app
    volumes:
      - "./:/app"
    restart: "no"
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8080
      FIRESTORE_PROJECT_ID: eventsauce
      DATASTORE_EMULATOR_HOST: datastore:8282
      DATASTORE_PROJECT_ID: eventsauce
    command: composer install
  firestore:
    image: mtlynch/firestore-emulator-docker
    container_name: eventsauce-messagestorage-gcp-firestore-emulator
    environment:
      PORT: 8080
      FIRESTORE_PROJECT_ID: eventsauce
    ports:
      - "8080:8080"
  datastore:
    image: egymgmbh/datastore-emulator
    container_name: eventsauce-messagestorage-gcp-datastore-emulator
    environment:
      PORT: 8282
      DATASTORE_PROJECT_ID: eventsauce
    ports:
      - "8282:8282"

