name: PHP Composer
on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        php_version: [ 8.1 ]
    runs-on: ubuntu-latest
    env:
      FIRESTORE_EMULATOR_HOST: localhost:8080
      FIRESTORE_PROJECT_ID: eventsauce
      DATASTORE_EMULATOR_HOST: localhost:8282
      DATASTORE_PROJECT_ID: eventsauce
    services:
      firestore:
        image: mtlynch/firestore-emulator-docker
        env:
          PORT: 8080
          FIRESTORE_PROJECT_ID: eventsauce
        ports:
          - 8080:8080
      datastore:
        image: egymgmbh/datastore-emulator
        env:
          PORT: 8282
          DATASTORE_PROJECT_ID: eventsauce
        ports:
          - 8282:8282
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show Env Variables
        run: echo $FIRESTORE_EMULATOR_HOST; echo $FIRESTORE_PROJECT_ID

      - name: Verify
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: phar, grpc
          coverage: none
          tools: composer:v2

      - name: Run composer verify
        run: composer verify